let Joi,CustomErorHandler,RefreshToken,User,brcypt,JwtService,REFRESH_SECRET;_c38‍.x([["default",()=>_c38‍.o]]);_c38‍.w("joi",[["default",["Joi"],function(v){Joi=v}]]);_c38‍.w("../../services/CustomErrorHandler",[["default",["CustomErorHandler"],function(v){CustomErorHandler=v}]]);_c38‍.w("../../models",[["RefreshToken",["RefreshToken"],function(v){RefreshToken=v}],["User",["User"],function(v){User=v}]]);_c38‍.w("bcrypt",[["default",["brcypt"],function(v){brcypt=v}]]);_c38‍.w("../../services/JwtService",[["default",["JwtService"],function(v){JwtService=v}]]);_c38‍.w("../../config",[["REFRESH_SECRET",["REFRESH_SECRET"],function(v){REFRESH_SECRET=v}]]);







const loginController = {
 async login(req, res, next) {

    const loginSchema = Joi.object({
        email : Joi.string().email().required(),
        password : Joi.string().pattern(new RegExp(/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/)).required()
    });
    const {error} = loginSchema.validate(req.body);

    if (error) {
        return next(error);    
    }
    try{
//whats happeing here ? a person sees many boxes in a shop (which is collection )
        const user = await User.findOne({email : req.body.email});
        if (!user) {
            return next(CustomErorHandler.wrongCredentials());
        }
        const match = await brcypt.compare(req.body.password, user.password);
        if (!match) {
            return next(CustomErorHandler.wrongCredentials());
        }

        const access_token = JwtService.sign({_id : user._id, role : user.role})
        const refresh_token = JwtService.sign({_id : user._id, role : user.role}, '1y', REFRESH_SECRET)
    
        await RefreshToken.create({token : refresh_token})


        res.json({access_token: access_token, refresh_token})



    } catch(err) {
       return next(err)
    }

 },

// Logout Controller


async logout(req,res,next) {

    const refreshSchema = Joi.object({refresh_token : Joi.string().required(),})
        
    const {error} = refreshSchema.validate(req.body);

    if(error) {
        return next(error)
    }



    try {
        await RefreshToken.deleteOne({token : req.body.refresh_token})
    } catch(err) {
        return next (new Error("Something went wrong"));
    }

    res.json({status : 1})
}



};




_c38‍.d(loginController);